extern const GeoLayout castle_courtyard_area_1_geo[];
extern const GeoLayout castle_courtyard_dl_1_geo[];
extern const GeoLayout castle_courtyard_dl_2_geo[];
extern const GeoLayout castle_courtyard_area_1[];
extern const Collision castle_courtyard_area_1_collision[];
extern const u8 castle_courtyard_area_1_collision_rooms[];
extern const MacroObject castle_courtyard_area_1_Area_1_macro_objs[];
extern Vtx castle_courtyard_dl_Main_Mesh_mesh_vtx_0[348];
extern Gfx castle_courtyard_dl_Main_Mesh_mesh_tri_0[];
extern Vtx castle_courtyard_dl_Main_Mesh_mesh_vtx_1[159];
extern Gfx castle_courtyard_dl_Main_Mesh_mesh_tri_1[];
extern Vtx castle_courtyard_dl_Main_Mesh_mesh_vtx_2[191];
extern Gfx castle_courtyard_dl_Main_Mesh_mesh_tri_2[];
extern Vtx castle_courtyard_dl_Water_Plane_mesh_vtx_0[4];
extern Gfx castle_courtyard_dl_Water_Plane_mesh_tri_0[];
extern Vtx castle_courtyard_dl_Sub_Room_1_mesh_vtx_0[150];
extern Gfx castle_courtyard_dl_Sub_Room_1_mesh_tri_0[];
extern Vtx castle_courtyard_dl_Sub_Room_1_mesh_vtx_1[108];
extern Gfx castle_courtyard_dl_Sub_Room_1_mesh_tri_1[];
extern Vtx castle_courtyard_dl_Sub_Room_1_mesh_vtx_2[70];
extern Gfx castle_courtyard_dl_Sub_Room_1_mesh_tri_2[];
extern Vtx castle_courtyard_dl_Water_Plane_2_mesh_vtx_0[4];
extern Gfx castle_courtyard_dl_Water_Plane_2_mesh_tri_0[];

extern Gfx castle_courtyard_dl_Main_Mesh_mesh[];
extern Gfx castle_courtyard_dl_Water_Plane_mesh[];
extern Gfx castle_courtyard_dl_Sub_Room_1_mesh[];
extern Gfx castle_courtyard_dl_Water_Plane_2_mesh[];
extern Gfx castle_courtyard_dl_material_revert_render_settings[];

