#include "src/game/envfx_snow.h"

const GeoLayout cannon_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, arm_cannon_RootBone_mesh),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, arm_cannon_CannonRing1End_skinned),
			GEO_ANIMATED_PART(1, 0, 0, -40, NULL),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(1, 0, 3, 0, -124, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(1, 0, 5, 0, 124, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, arm_cannon_CannonRing1End_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(1, arm_cannon_CannonRing2End_skinned),
								GEO_ANIMATED_PART(1, 0, 0, -6, NULL),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(1, 0, 3, 0, -124, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_TRANSLATE_ROTATE(1, 0, 5, 0, 124, 0, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 0, 0, 0, arm_cannon_CannonRing2End_mesh),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(1, arm_cannon_CannonRing3End_skinned),
													GEO_ANIMATED_PART(1, 0, 0, -11, NULL),
													GEO_OPEN_NODE(),
														GEO_TRANSLATE_ROTATE(1, 0, 3, 0, -124, 0, 0),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_TRANSLATE_ROTATE(1, 0, 5, 0, 124, 0, 0),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(1, 0, 0, 0, arm_cannon_CannonRing3End_mesh),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(1, -2, 0, -17, NULL),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(1, 0, 3, 0, 0, 0, 149),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(1, 0, 4, 0, 0, 0, -149),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, arm_cannon_CannonSideEnd_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(1, 0, 2, -14, 90, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(1, 0, 3, 0, -159, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(1, 0, 3, 0, 69, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, arm_cannon_CannonTopEnd_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, arm_cannon_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, arm_cannon_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, arm_cannon_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, arm_cannon_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, arm_cannon_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, arm_cannon_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, arm_cannon_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, arm_cannon_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
