#include "src/game/envfx_snow.h"

const GeoLayout castle_courtyard_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, castle_courtyard_dl_1_geo),
			GEO_BRANCH(1, castle_courtyard_dl_2_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_courtyard_dl_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(1, 0, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE_WITH_DL(1, 0, 0, 0, 0, 0, 0, castle_courtyard_dl_Main_Mesh_mesh),
			GEO_TRANSLATE_ROTATE_WITH_DL(5, -3155, 46, 3774, 0, 0, 0, castle_courtyard_dl_Water_Plane_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_courtyard_dl_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(1, -7676, 222, 528, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE_WITH_DL(1, 3977, -222, -528, 0, 0, 0, castle_courtyard_dl_Sub_Room_1_mesh),
			GEO_TRANSLATE_ROTATE_WITH_DL(5, -293, 18, -119, 0, 0, 0, castle_courtyard_dl_Water_Plane_2_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_courtyard_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_GREEN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 10, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, castle_courtyard_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, castle_courtyard_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, castle_courtyard_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, castle_courtyard_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, castle_courtyard_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, castle_courtyard_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, castle_courtyard_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, castle_courtyard_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, castle_courtyard_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
